/*
Panel principal del proyecto
 */
package aero_mariano;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;



/**
 *
 * @author Mariano
 */
public class aeroPanel extends javax.swing.JFrame {

    int asientos[] = {1,2,3,4,5,6,7,8,9,10};
    int arreglo_asiento;
    String reservaciones[] = {"[ ▒ ]","[ ▒ ]","[ ▒ ]","[ ▒ ]","[ ▒ ]","[ ▒ ]","[ ▒ ]","[ ▒ ]","[ ▒ ]","[ ▒ ]"};
   
    /**
     * Creates new form aeroPanel
     */
    public aeroPanel() 
    {
        /*----------------------------------------------------------------------
        |                  Esto determina el panel principal
        ----------------------------------------------------------------------*/
        
        //OCUPADO ASCII
        //█
        //OCUPADO ASCII
        //▒
        
        initComponents();
        //Pone un icono en la barra de tareas
        setIconImage(new ImageIcon(getClass().getResource("../Recursos/AvionIcono.png")).getImage());
        
        txtaPanel.setText("Primera Clase:\n");
        for (int i = 0; i < 5; i++) 
        {
            //Asientos disponibles
            txtaPanel.append("\t"+ asientos[i] + "[ ▒ ]"); 
        }
        txtaPanel.append("\nSegunda Clase:\n");
        for (int m = 0; m < 10; m++) 
        {
            if (asientos[m] >= 6) 
            {
                txtaPanel.append("\t" + asientos[m] + "[ ▒ ]");
            }
        }
        
        txtaPanel.append("\n");
        txtaPanel.append("\n");
        txtaPanel.append("\n");
        txtaPanel.append("\n\t\t\tASIENTOS DISPONIBLES: [ ▒ ]");
        txtaPanel.append("\n\t\t\tASIENTOS OCUPADOS: [ █ ]");
        
        
        
        
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtaPanel = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        btnReservar = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();
        btnRegistros = new javax.swing.JButton();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(3, 169, 244));
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("TimeBurner", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Aire-Lines");
        jLabel1.setToolTipText("");

        txtaPanel.setBackground(new java.awt.Color(179, 224, 252));
        txtaPanel.setColumns(20);
        txtaPanel.setRows(5);
        jScrollPane1.setViewportView(txtaPanel);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/nubes.jpg"))); // NOI18N

        btnReservar.setText("Reservar");
        btnReservar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReservarActionPerformed(evt);
            }
        });

        btnSalir.setText("Salir");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        btnRegistros.setText("Ver registros");
        btnRegistros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(100, 100, 100)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 544, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnReservar, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(128, 128, 128)
                                .addComponent(btnRegistros, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18))
                            .addComponent(jScrollPane1)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 718, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(17, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE, false)
                    .addComponent(btnReservar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnRegistros, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnSalir))
                .addContainerGap(39, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>                        

    private void btnReservarActionPerformed(java.awt.event.ActionEvent evt) {                                            
        
        /*-------------------------------------------------------------------*/
        /*--------------------- BOTON DE RESERVAR   -------------------------*/
        /*-------------------------------------------------------------------*/
        
        //NUMERO DE ASIENTO
        arreglo_asiento = Integer.parseInt(JOptionPane.showInputDialog(null,"¿Que asiento quieres?"));
        //Para que verifique si está ocupado el asientos
        for (int m = 0; m < 10; m++) 
        {
            if (arreglo_asiento == asientos[m] && reservaciones[m] == "[ █ ]") 
            {
                JOptionPane.showMessageDialog(null,"ASIENTO RESERVADO PREVIAMENTE");
            }
        }
        txtaPanel.setText("Primera Clase:\n");
        
        //VALIDACION
        //Modifica los primeros 5 registros del arreglo
        for (int m =0; m < 5; m++) 
        {
            //OCUPADO
            if (arreglo_asiento == asientos[m]) 
            {
                txtaPanel.append(" "+ asientos[m]);
                //Valor en posicion del vector numerico
                reservaciones[m] = "[ █ ]";
                
            }
            //Imprime el vector de los codigos ascii
            txtaPanel.append("\t" + asientos[m] + reservaciones[m]);
            
        }
        
        txtaPanel.append("\nSegunda Clase:\n");
        for (int m = 0; m < 10; m++) 
        {
            if (asientos[m] >= 6)
            {
                //OCUPADO
                if (arreglo_asiento == asientos[m]) 
                {
                    txtaPanel.append(" "+ asientos[m]);
                    //Valor en posicion del vector numerico
                    reservaciones[m] = "[ █ ]";
                }
                //Imprime el vector de los codigos ascii
                txtaPanel.append("\t" + asientos[m] + reservaciones[m]);
            }   
        }
        
        txtaPanel.append("\n");
        txtaPanel.append("\n");
        txtaPanel.append("\n");
        txtaPanel.append("\n\t\t\tASIENTOS DISPONIBLES: [ ▒ ]");
        txtaPanel.append("\n\t\t\tASIENTOS OCUPADOS: [ █ ]");
        //Opcion de clase
        opcionVuelo opcion = new opcionVuelo();
        
        opcion.setVisible(true);
        
    }                                           

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {                                         
        
        /*-------------------------------------------------------------------*/
        /*--------------------- BOTON DE SALIR   ----------------------------*/
        /*-------------------------------------------------------------------*/
        System.exit(0);
    }                                        

    private void btnRegistrosActionPerformed(java.awt.event.ActionEvent evt) {                                             
        /*-------------------------------------------------------------------*/
        /*--------------------- BOTON REGSITROS   ----------------------------*/
        /*-------------------------------------------------------------------*/
        
        registrosVuelo registros = new registrosVuelo();
        
        
        registros.setVisible(true);
        
        
        
    }                                            

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(aeroPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(aeroPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(aeroPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(aeroPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new aeroPanel().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JButton btnRegistros;
    private javax.swing.JButton btnReservar;
    private javax.swing.JButton btnSalir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea txtaPanel;
    // End of variables declaration                   
}
