/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package aero_mariano;
import javax.swing.ImageIcon;
import java.awt.BorderLayout; //Para poder poner una imagen de fondo 

/**
 *
 * @author Mariano
 */
public class opcionVuelo extends javax.swing.JFrame {

    /**
     * Creates new form opcionVuelo
     */
    public opcionVuelo() {
        initComponents();
        //Pone un icono en la barra de tareas
        setIconImage(new ImageIcon(getClass().getResource("../Recursos/AvionIcono.png")).getImage());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnClaseNormal = new javax.swing.JButton();
        btnPrimeraClase = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Clase de vuelo");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        btnClaseNormal.setText("Clase Normal");
        btnClaseNormal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClaseNormalActionPerformed(evt);
            }
        });

        btnPrimeraClase.setText("Primera Clase");
        btnPrimeraClase.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrimeraClaseActionPerformed(evt);
            }
        });

        jButton1.setText("Cancelar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(btnPrimeraClase)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 81, Short.MAX_VALUE)
                .addComponent(btnClaseNormal)
                .addGap(58, 58, 58))
            .addGroup(layout.createSequentialGroup()
                .addGap(153, 153, 153)
                .addComponent(jButton1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(196, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnPrimeraClase)
                    .addComponent(btnClaseNormal))
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addGap(22, 22, 22))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnPrimeraClaseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrimeraClaseActionPerformed
        
        /*-------------------------------------------------------------------*/
        /*-------------- BOTON DE RESERVA PRIMERA CLASE ---------------------*/
        /*-------------------------------------------------------------------*/
        
        //Carga la pagina de registro
        reservacionViajeP reservacionPrimera = new reservacionViajeP();
        
        reservacionPrimera.setVisible(true);
        
        //Cierra la actual
        //this.setVisible(false);
        
        
    }//GEN-LAST:event_btnPrimeraClaseActionPerformed

    private void btnClaseNormalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClaseNormalActionPerformed
        
        /*-------------------------------------------------------------------*/
        /*-------------- BOTON DE RESERVA CLASE NORMAL  ---------------------*/
        /*-------------------------------------------------------------------*/
        
        //Carga la pagina de registro
        reservaViaje reservacion = new reservaViaje();
        
        reservacion.setVisible(true);
        
        //Cierra la actual
        //this.setVisible(false);
        
        
    }//GEN-LAST:event_btnClaseNormalActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        /*-------------------------------------------------------------------*/
        /*-------------------- FONDO DE LA OPCION  ---------------------------*/
        /*-------------------------------------------------------------------*/
        /*
        FondoOpcion fondo_o = new FondoOpcion();
        
        this.add(fondo_o, BorderLayout.SOUTH);
        fondo_o.repaint();
        */
    }//GEN-LAST:event_formWindowOpened

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        /*-------------------------------------------------------------------*/
        /*-------------------- BOTÓN CANCELAR  ---------------------------*/
        /*-------------------------------------------------------------------*/
        
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(opcionVuelo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(opcionVuelo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(opcionVuelo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(opcionVuelo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new opcionVuelo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClaseNormal;
    private javax.swing.JButton btnPrimeraClase;
    private javax.swing.JButton jButton1;
    // End of variables declaration//GEN-END:variables
}
