/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package aero_mariano;
import Conexion.Conexion;
import java.sql.ResultSet;
import java.util.HashMap;
import java.util.Map;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import net.sf.jasperreports.engine.JREmptyDataSource;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.util.JRLoader;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author Mariano
 */
public class registrosVuelo extends javax.swing.JFrame {

    /**
     * Creates new form regsitrosVuelo
     */
    public registrosVuelo() {
        initComponents();
        //Pone un icono en la barra de tareas
        setIconImage(new ImageIcon(getClass().getResource("../Recursos/AvionIcono.png")).getImage());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tabla = new javax.swing.JTable();
        btnRegresar = new javax.swing.JButton();
        btnActualizarRegistros1 = new javax.swing.JButton();
        btnReportes = new javax.swing.JButton();
        lblReportes = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tabla);

        btnRegresar.setText("Regresar");
        btnRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarActionPerformed(evt);
            }
        });

        btnActualizarRegistros1.setText("Actualizar Registros");
        btnActualizarRegistros1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarRegistros1ActionPerformed(evt);
            }
        });

        btnReportes.setText("Generar Reporte");
        btnReportes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReportesActionPerformed(evt);
            }
        });

        lblReportes.setText("Reporte de reservaciones");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(81, 81, 81)
                .addComponent(btnActualizarRegistros1)
                .addGap(70, 70, 70)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnReportes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblReportes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 89, Short.MAX_VALUE)
                .addComponent(btnRegresar, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(98, 98, 98))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 68, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRegresar)
                    .addComponent(btnActualizarRegistros1)
                    .addComponent(btnReportes))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblReportes)
                .addGap(15, 15, 15))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarActionPerformed
        
        /*-------------------------------------------------------------------*/
        /*----------------------- BOTON REGRESAR  ---------------------------*/
        /*-------------------------------------------------------------------*/
        this.dispose();
    }//GEN-LAST:event_btnRegresarActionPerformed

    private void btnActualizarRegistros1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarRegistros1ActionPerformed
        
        /*-------------------------------------------------------------------*/
        /*------------------ BOTON ACTUALIZAR REGISTROS  --------------------*/
        /*-------------------------------------------------------------------*/
        
        //Instancia
        Conexion c = new Conexion();
        //Inicio de conexion
        c.conexionDB();
        //Query a ejecutar
        ResultSet consulta = c.consulta("SELECT * FROM reservaciones");
        
        try
        {
            //Objeto tabla
            DefaultTableModel tabla = new DefaultTableModel();
            //Agregar columnas especificas al objeto
            tabla.addColumn("Id");
            tabla.addColumn("Clase");
            tabla.addColumn("Destino");
            tabla.addColumn("Asiento");
            tabla.addColumn("Precio");
            tabla.addColumn("Nombre");
            tabla.addColumn("Apellido Paterno");
            tabla.addColumn("Apellido Materno");
            tabla.addColumn("Edad");
            tabla.addColumn("Sexo");
            
            while(consulta.next())
            {
                Object[] fila = new Object[10];
                fila[0] = consulta.getString(1);//ID
                fila[1] = consulta.getString(2);//CLASE
                fila[2] = consulta.getString(3);//DESTINO
                fila[3] = consulta.getString(4);//ASIENTO
                fila[4] = consulta.getString(5);//PRECIO
                fila[5] = consulta.getString(6);//NOMBRE
                fila[6] = consulta.getString(7);//APELLIDO1
                fila[7] = consulta.getString(8);//APELLIDO2
                fila[8] = consulta.getString(9);//EDAD
                fila[9] = consulta.getString(10);//SEXO
                tabla.addRow(fila);
            }
            this.tabla.setModel(tabla);
            
        }catch(Exception ex)
        {
            
        }
    }//GEN-LAST:event_btnActualizarRegistros1ActionPerformed

    private void btnReportesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReportesActionPerformed
        /*-------------------------------------------------------------------*/
        /*------------------ BOTON GENERAR REPORTES   -----------------------*/
        /*-------------------------------------------------------------------*/
        
        try
        {
            //Ubicacion del reporte
            //Se hace un casteo para que devuelva un tipo jasperreport...
            JasperReport reporte = (JasperReport) JRLoader.loadObject(registrosVuelo.class.getResource("../aero_mariano/ReservacionesReportes.jasper"));
            
            //Se especifica el tipo de datos de lo que traera de info
            Map parametros = new HashMap<String, Object>();
            //Se deben de poner la lista de parametros a mostrar exactamente como se
            //definieron en el reporte
            parametros.put("Nombre", lblReportes.getText());//Se le dice de donde tomar los datos
            
            JasperPrint reporte_completo = JasperFillManager.fillReport(reporte, parametros,new JREmptyDataSource());//El objeto/la info/oigen de info
            
            //Mostrarlo
            JasperViewer vista_reporte = new JasperViewer(reporte_completo);
            vista_reporte.show();
                
        }catch(Exception ex)
        {
            JOptionPane.showMessageDialog(null,"ERROR, CONTACTE A MARIANO" + ex.getMessage());
        }
        
        
        
        
        
        
        
        
        
        
        
        
        
    }//GEN-LAST:event_btnReportesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(registrosVuelo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(registrosVuelo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(registrosVuelo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(registrosVuelo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new registrosVuelo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualizarRegistros1;
    private javax.swing.JButton btnRegresar;
    private javax.swing.JButton btnReportes;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblReportes;
    private javax.swing.JTable tabla;
    // End of variables declaration//GEN-END:variables
}
