/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package aero_mariano;
import Conexion.Conexion;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author Mariano
 */
public class reservacionViajeP extends javax.swing.JFrame {

    /**
     * Creates new form reservacionViajeP
     */
    public reservacionViajeP() {
        initComponents();
        //Pone un icono en la barra de tareas
        setIconImage(new ImageIcon(getClass().getResource("../Recursos/AvionIcono.png")).getImage());
    }
    
    public void LimpiarCajasRegistro()
    {
        txtfDestinoPrimeraClase.setText("");
        txtfNombrePrimeraClase.setText("");
        txtfApellidoPPrimeraClase.setText("");
        txtfApellidoMPrimeraClase.setText("");
        txtfEdadPrimeraClase.setText("");
        txtfSexoPrimeraClase.setText("");
        txtfAsientoPrimeraClase.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtfApellidoMPrimeraClase = new javax.swing.JTextField();
        lblClasePrimera = new javax.swing.JLabel();
        txtfClasePrimeraClase = new javax.swing.JTextField();
        lblSexoClasePrimera = new javax.swing.JLabel();
        lblEdadClasePriemera = new javax.swing.JLabel();
        lblPrecioPrimera = new javax.swing.JLabel();
        lblNombreClasePrimera = new javax.swing.JLabel();
        txtfPrecioPrimeraClase = new javax.swing.JTextField();
        txtfSexoPrimeraClase = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtfEdadPrimeraClase = new javax.swing.JTextField();
        txtfNombrePrimeraClase = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        lblApellidoPaternoClasePrimera = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        txtfApellidoPPrimeraClase = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        lblApellidoPaternoClaseMaternoPrimera = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtfDestinoPrimeraClase = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtfAsientoPrimeraClase = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        txtfApellidoMPrimeraClase.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtfApellidoMPrimeraClaseActionPerformed(evt);
            }
        });

        lblClasePrimera.setText("Clase:");

        txtfClasePrimeraClase.setEditable(false);
        txtfClasePrimeraClase.setText("Primera Clase");

        lblSexoClasePrimera.setText("Sexo:");

        lblEdadClasePriemera.setText("Edad:");

        lblPrecioPrimera.setText("Precio:");

        lblNombreClasePrimera.setText("Nombre:");

        txtfPrecioPrimeraClase.setEditable(false);
        txtfPrecioPrimeraClase.setText("2500");
        txtfPrecioPrimeraClase.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtfPrecioPrimeraClaseActionPerformed(evt);
            }
        });

        txtfSexoPrimeraClase.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtfSexoPrimeraClaseActionPerformed(evt);
            }
        });

        jLabel10.setText("$");

        txtfEdadPrimeraClase.setText("00");
        txtfEdadPrimeraClase.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtfEdadPrimeraClaseActionPerformed(evt);
            }
        });

        txtfNombrePrimeraClase.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtfNombrePrimeraClaseActionPerformed(evt);
            }
        });

        jLabel5.setText("años");

        lblApellidoPaternoClasePrimera.setText("Apellido Paterno:");

        jLabel1.setFont(new java.awt.Font("TimeBurner", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Aire-Lines");

        jButton1.setText("Reservar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        txtfApellidoPPrimeraClase.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtfApellidoPPrimeraClaseActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("TimeBurner", 1, 24)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("--Registro--");

        jButton2.setText("Cancelar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        lblApellidoPaternoClaseMaternoPrimera.setText("Apellido Materno:");

        jLabel4.setText("Destino:");

        jLabel3.setText("Asiento:");

        jLabel6.setText("[H] Hombre -- [M] Mujer");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblClasePrimera)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(2, 2, 2)
                                .addComponent(jLabel4))
                            .addComponent(jLabel3))
                        .addGap(61, 61, 61)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtfClasePrimeraClase, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(txtfDestinoPrimeraClase)
                            .addComponent(txtfAsientoPrimeraClase)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblApellidoPaternoClaseMaternoPrimera)
                                    .addComponent(lblEdadClasePriemera, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblSexoClasePrimera))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtfApellidoMPrimeraClase, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(txtfEdadPrimeraClase)
                                            .addComponent(txtfSexoPrimeraClase))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel6)))))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(lblNombreClasePrimera, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtfNombrePrimeraClase, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(lblApellidoPaternoClasePrimera)
                                    .addGap(18, 18, 18)
                                    .addComponent(txtfApellidoPPrimeraClase, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(lblPrecioPrimera)
                                    .addGap(74, 74, 74)
                                    .addComponent(jLabel10)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(txtfPrecioPrimeraClase, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(36, 36, 36)))
                .addContainerGap(33, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(55, 55, 55)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jButton1)
                            .addGap(107, 107, 107)
                            .addComponent(jButton2))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(93, 93, 93)
                            .addComponent(jLabel2))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(107, 107, 107)
                            .addComponent(jLabel1)))
                    .addContainerGap(102, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(101, 101, 101)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblClasePrimera)
                    .addComponent(txtfClasePrimeraClase, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtfDestinoPrimeraClase, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtfAsientoPrimeraClase, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblPrecioPrimera)
                        .addComponent(txtfPrecioPrimeraClase, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel10))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblNombreClasePrimera, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtfNombrePrimeraClase, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblApellidoPaternoClasePrimera, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtfApellidoPPrimeraClase, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblApellidoPaternoClaseMaternoPrimera, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtfApellidoMPrimeraClase, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEdadClasePriemera, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtfEdadPrimeraClase, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSexoClasePrimera)
                    .addComponent(txtfSexoPrimeraClase, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(50, 50, 50))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jLabel1)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addComponent(jLabel2)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 370, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButton1)
                        .addComponent(jButton2))
                    .addContainerGap()))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtfApellidoMPrimeraClaseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtfApellidoMPrimeraClaseActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtfApellidoMPrimeraClaseActionPerformed

    private void txtfPrecioPrimeraClaseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtfPrecioPrimeraClaseActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtfPrecioPrimeraClaseActionPerformed

    private void txtfSexoPrimeraClaseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtfSexoPrimeraClaseActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtfSexoPrimeraClaseActionPerformed

    private void txtfEdadPrimeraClaseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtfEdadPrimeraClaseActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtfEdadPrimeraClaseActionPerformed

    private void txtfNombrePrimeraClaseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtfNombrePrimeraClaseActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtfNombrePrimeraClaseActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        /*-------------------------------------------------------------------*/
        /*----------------------- BOTON DE RESERVA  -------------------------*/
        /*-------------------------------------------------------------------*/
         
       //Instancia
       Conexion guardar = new Conexion();
       //Objeto
       Connection conexion = guardar.conexionDB();
       String sql="";
       
       String clase,destino,asiento,precio,nombre,apellido_p,apellido_m,edad,sexo;
       
       clase = txtfClasePrimeraClase.getText();
       destino = txtfDestinoPrimeraClase.getText();
       asiento = txtfAsientoPrimeraClase.getText();
       precio = txtfPrecioPrimeraClase.getText();
       nombre = txtfNombrePrimeraClase.getText();
       apellido_p = txtfApellidoPPrimeraClase.getText();
       apellido_m = txtfApellidoMPrimeraClase.getText();
       edad = txtfEdadPrimeraClase.getText();
       sexo = txtfSexoPrimeraClase.getText();
       //ObtenerTexto();
       
       sql = "INSERT INTO reservaciones (clase,destino,asiento,precio,nombre,apellido_p,apellido_m,edad,sexo) VALUES (?,?,?,?,?,?,?,?,?)";
       
        try 
        {
            PreparedStatement orden = conexion.prepareStatement(sql);
            orden.setString(1,clase);
            orden.setString(2,destino);
            orden.setString(3,asiento);
            orden.setString(4,precio);
            orden.setString(5,nombre);
            orden.setString(6,apellido_p);
            orden.setString(7,apellido_m);
            orden.setString(8,edad);
            orden.setString(9,sexo);
            
            int m = orden.executeUpdate(); //Si se guardo exitosamente se guarda un 1
            
            if (m > 0) 
            {
                JOptionPane.showMessageDialog(null,"Registro EXITOSO");
                LimpiarCajasRegistro(); //Limpia los campos
            }
            
        } catch (SQLException ex) 
        {
            Logger.getLogger(reservaViaje.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void txtfApellidoPPrimeraClaseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtfApellidoPPrimeraClaseActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtfApellidoPPrimeraClaseActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

        /*-------------------------------------------------------------------*/
        /*-------------- BOTON DE CANCELAR RESERVACION  ---------------------*/
        /*-------------------------------------------------------------------*/
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(reservacionViajeP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(reservacionViajeP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(reservacionViajeP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(reservacionViajeP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new reservacionViajeP().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel lblApellidoPaternoClaseMaternoPrimera;
    private javax.swing.JLabel lblApellidoPaternoClasePrimera;
    private javax.swing.JLabel lblClasePrimera;
    private javax.swing.JLabel lblEdadClasePriemera;
    private javax.swing.JLabel lblNombreClasePrimera;
    private javax.swing.JLabel lblPrecioPrimera;
    private javax.swing.JLabel lblSexoClasePrimera;
    private javax.swing.JTextField txtfApellidoMPrimeraClase;
    private javax.swing.JTextField txtfApellidoPPrimeraClase;
    private javax.swing.JTextField txtfAsientoPrimeraClase;
    private javax.swing.JTextField txtfClasePrimeraClase;
    private javax.swing.JTextField txtfDestinoPrimeraClase;
    private javax.swing.JTextField txtfEdadPrimeraClase;
    private javax.swing.JTextField txtfNombrePrimeraClase;
    private javax.swing.JTextField txtfPrecioPrimeraClase;
    private javax.swing.JTextField txtfSexoPrimeraClase;
    // End of variables declaration//GEN-END:variables
}
